M48
; DRILL file {KiCad (6.0.5)} date Tue Dec  6 20:58:18 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-06T20:58:18-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.0551Y-4.685
X5.1321Y-3.7707
X5.14Y-2.2636
X8.1141Y-2.4214
X8.1141Y-3.9371
T0
M30
